helmDefaults:
  createNamespace: true
  wait: true
  timeout: 600
  


repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  
  - name: cert-manager
    url: https://charts.jetstack.io

  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/

  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: "4.14.1"
    values:
      - helm-values/nginx-ingress.yaml
  
  - name: cert-manager
    namespace: cert-manager
    chart: cert-manager/cert-manager
    version: "1.19.2"
    values: 
      - helm-values/cert-manager.yaml 
    
  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    version: "1.20.0"
    values:
      - helm-values/external-dns.yaml

  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: "9.3.4"
    values: 
      - helm-values/argo-cd.yaml 


