#This yaml file registers an application with argocd and tells it watch this git repo
#take the kubernetes manifests in this folder (deployment/apps) and deploy them into the namespace
#argocd
apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
  name: app1
  namespace: argocd #use argocd name space to add the resources
spec:
  project: default #the project the application belongs to
  source: #desired state in git
    repoURL: https://github.com/Ismail-1630672/K8s-Cluster.git 
    targetRevision: HEAD #use the latest commit on the default branch
    path: deployment/apps
  destination: #where to deploy, basically reference to the target cluster and namespace
    server: https://kubernetes.default.svc #points to kubernetes API server
    namespace: deployment 
  
  #now control how argo cd keeps the cluster in sync with git 
  syncPolicy:
    automated: #enables automatic sync rather than manual button
      enabled: true 
      prune: true #deletes resources from cluster that were removed from git
      selfHeal: true #fixes configuration drift automatically, for example if someone runs kubectl edit deployment my-app
      #the live cluster will then differ from git, argo cd will revert back to what is in git. 
      #This ensures git remains as the single source of truth
    syncOptions:
    - CreateNameSpace=true #this ensures the namespace destination.namespace exists in the cluster